# Generated by Django 4.0 on 2021-12-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
                ('m_price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('m_description', models.TextField()),
                ('m_quantity', models.CharField(max_length=50)),
                ('m_manufacturedate', models.DateTimeField()),
                ('m_expirydate', models.DateTimeField()),
            ],
        ),
    ]
