# Generated by Django 4.0 on 2021-12-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='m_expirydate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='m_manufacturedate',
            field=models.DateField(),
        ),
    ]
