# Generated by Django 4.0 on 2021-12-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('delivery_app', '0003_medicine_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=13)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('product', models.ManyToManyField(to='delivery_app.Medicine')),
            ],
        ),
    ]
